/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.regex.Pattern;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author sopor
 */
public class Ventana1 extends javax.swing.JDialog {

    /**
     * Creates new form Ventana1
     */
    public Ventana1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Elegir Proveedor");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int cont = 0;
        int num = 0;

        System.out.println("jTable1.getRowCount() " + Ventana1.jTable1.getRowCount());
        System.out.println("jTable1.getColumnCount() " + Ventana1.jTable1.getColumnCount());

        for (int i = 0; i < Ventana1.jTable1.getRowCount(); i++) {
            System.out.println("i " + i);
            String toString = Ventana1.jTable1.getValueAt(i, 3).toString();
            System.out.println("toString " + toString);
            if (Ventana1.jTable1.getValueAt(i, 3).equals(true)) {
                System.out.println("Es true");
                cont = cont + 1;
                num = i;
            }
        }

        System.out.println("cont " + cont);

        if (cont > 1 || cont == 0) {
            JOptionPane.showMessageDialog(this, "DEBE ELEGIR UN PRECIO", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            System.out.println("Aqui Ventana");
            VentanaPrincipal.codigoVentana1 = Ventana1.jTable1.getValueAt(num, 1).toString();
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Proveedor");
        model.addColumn("Codigo");
        model.addColumn("Precio");
        model.addColumn("Elegir");

        Object[] fila = new Object[4];
        for (int i = 0; i < VentanaPrincipal.paquete.size(); i++) {
            fila[0] = VentanaPrincipal.paquete.get(i).get(0);
            fila[1] = VentanaPrincipal.paquete.get(i).get(1);
            String get = (String) VentanaPrincipal.paquete.get(i).get(2);
            if (get.length() > 0) {
                fila[2] = VentanaPrincipal.paquete.get(i).get(2);
                fila[3] = false;
            } else {
                fila[2] = "NO ENCONTRADO";
                fila[3] = false;
            }
            model.addRow(fila);
        }

        Ventana1.jTable1.setModel(model);

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();

        centerRenderer.setHorizontalAlignment(JLabel.CENTER);

        TableRowSorter trs = new TableRowSorter(model);

        class IntComparator implements Comparator {

            public int compare(Object o1, Object o2) {
                Integer int1 = (Integer) o1;
                Integer int2 = (Integer) o2;
                return int1.compareTo(int2);
            }

            public boolean equals(Object o2) {
                return this.equals(o2);
            }
        }

        class IntComparator2 implements Comparator {

            public int compare(Object o1, Object o2) {
                Double valueOf = Double.valueOf(o1.toString());
                Double valueOf1 = Double.valueOf(o2.toString());
                double name = valueOf * 100;
                double name2 = valueOf1 * 100;
                String valueOf2 = String.valueOf(name);
                String[] split = valueOf2.split(Pattern.quote("."));
                String valueOf3 = String.valueOf(name2);
                String[] split2 = valueOf3.split(Pattern.quote("."));

                Integer int1 = (Integer) Integer.valueOf(String.valueOf(split[0]));
                Integer int2 = (Integer) Integer.valueOf(String.valueOf(split2[0]));
                return int1.compareTo(int2);
            }

            public boolean equals(Object o2) {
                return this.equals(o2);
            }
        }

        trs.setComparator(2, new IntComparator());

        Ventana1.jTable1.setRowSorter(trs);
        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) Ventana1.jTable1.getTableHeader().getDefaultRenderer();

        renderer.setHorizontalAlignment(JLabel.CENTER);

        Ventana1.jTable1.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        Ventana1.jTable1.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        Ventana1.jTable1.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        Ventana1.jTable1.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        Ventana1.jTable1.getColumnModel().getColumn(0).setPreferredWidth(220);
        Ventana1.jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
        TableColumn Tcol = Ventana1.jTable1.getColumnModel().getColumn(3);

        Tcol.setCellEditor(Ventana1.jTable1.getDefaultEditor(Boolean.class));
        Tcol.setCellRenderer(Ventana1.jTable1.getDefaultRenderer(Boolean.class));
        Ventana1.jTable1.setRowHeight(25);
        Ventana1.jTable1.setShowHorizontalLines(true);
        Ventana1.jTable1.setShowVerticalLines(true);
    }//GEN-LAST:event_formWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
